version: "2.2"

services:
  traefik:
    image: traefik:v2.10
    container_name: traefik
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./traefik.yml:/etc/traefik/traefik.yml:ro
      - ./dynamic.yml:/etc/traefik/dynamic/dynamic.yml:ro
      - traefik-certificates:/etc/traefik/certificates
    networks:
      - traefik-public
    deploy:
      resources:
        limits:
          memory: 1G
          cpus: '2'
        reservations:
          cpus: '2'

  app:
    build: .
    restart: unless-stopped
    networks:
      - traefik-public
    deploy:
      resources:
        limits:
          memory: 2G
          cpus: '2'
        reservations:
          cpus: '1'
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.weddingdirectory-http.rule=Host(`weddingdirectoryfl.com`) || Host(`www.weddingdirectoryfl.com`)"
      - "traefik.http.routers.weddingdirectory-http.entrypoints=web"
      - "traefik.http.routers.weddingdirectory-http.middlewares=redirect-to-https"
      - "traefik.http.routers.weddingdirectory-https.rule=Host(`weddingdirectoryfl.com`) || Host(`www.weddingdirectoryfl.com`)"
      - "traefik.http.routers.weddingdirectory-https.entrypoints=websecure"
      - "traefik.http.routers.weddingdirectory-https.tls.certresolver=letsencrypt"
      - "traefik.http.services.weddingdirectory.loadbalancer.server.port=3000"
      - "traefik.http.middlewares.redirect-to-https.redirectscheme.scheme=https"
      - "traefik.http.middlewares.redirect-to-https.redirectscheme.permanent=true"

networks:
  traefik-public:
    external: true

volumes:
  traefik-certificates: 