[phases.setup]
nixPkgs = ['nodejs_18']

[phases.install]
cmds = ['chmod +x build.sh']

[phases.build]
cmds = ['./build.sh']

[start]
cmd = 'npm start'

[variables]
NODE_ENV = 'production'
MONGODB_URI = '${MONGODB_URI}' 